// enableFeaturePreview("TYPESAFE_PROJECT_ACCESSORS")

pluginManagement {
    repositories {
        google()
        mavenCentral()
        mavenLocal()
        gradlePluginPortal()
        maven("https://maven.pkg.jetbrains.space/public/p/compose/dev")
    }
}
dependencyResolutionManagement {
//    repositoriesMode.set(RepositoriesMode.PREFER_SETTINGS)
    repositories {
        google()
        mavenCentral()
        mavenLocal()
        maven("https://maven.pkg.jetbrains.space/public/p/compose/dev")
    }
}

rootProject.name = "Writeopia"

include(":writeopia")
include(":writeopia_models")
include(":writeopia_ui")
include(":plugins:writeopia_persistence_room")
include(":plugins:writeopia_serialization")
include(":plugins:writeopia_network")
include(":plugins:writeopia_export")
include(":plugins:writeopia_import_document")
include(":plugins:writeopia_persistence_core")
include(":plugins:writeopia_persistence_sqldelight")
include(":application:core:resources")
include(":application:core:auth_core")
include(":application:core:utils")
include(":application:core:common_ui")
include(":application:core:common_ui_tests")
include(":application:core:persistence_room")
include(":application:core:persistence_sqldelight")
include(":application:core:persistence_bridge")
include(":application:features:account")
include(":application:features:editor")
include(":application:features:global_shell")
include(":application:features:note_menu")
include(":application:features:auth")
include(":application:common_flows:wide_screen_common")
include(":application:web")
include(":libraries:dbtest")
include(":backend:editor:api_editor_socket")
include(":common:endpoints")
include(":application:core:theme")
include(":application:core:navigation")
include(":application:features:search")
include(":application:features:notifications")
include(":application:features:update")
include(":plugins:writeopia_presentation")
include(":application:core:models")
include(":application:composeApp")
include(":application:androidApp")
include(":application:core:documents")
include(":application:core:connection")
include(":application:core:local_ai")
include(":application:core:genai")
include(":tutorials")
include(":application:features:onboarding")
include(":backend:documents:documents")
include(":backend:core:auth")
include(":backend:core:ai")
include(":backend:core:genai_service")
include(":backend:gateway")
include(":backend:micro:auth")
include(":backend:micro:documents")
include(":application:core:configuration")
include(":backend:core:database")
include(":backend:core:connection")
include(":application:core:forcegraph")
include(":application:features:documents_graph")
include(":application:features:drawing")
include(":backend:core:buckets")
include(":backend:core:models")
include(":backend:micro:media")
include(":backend:micro:export")
include(":backend:micro:ai")
